version: "3"

services:
  strava_threshold_zones_api_db:
    container_name: strava_threshold_zones_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=matt
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=strava_threshold_zones
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    volumes:
      - stravathresholddb:/var/lib/postgresql/data

volumes:
  stravathresholddb:
