version: "3"

services:
  strava_threshold_zones_api_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=matt
      - POSTGRES_PASSWORD=topsecret
    entrypoint: sh -c "
      echo \"psql -v ON_ERROR_STOP=1 --username matt --dbname postgres <<-EOSQL\n
      CREATE DATABASE strava_threshold_zones;\n
      GRANT ALL PRIVILEGES ON DATABASE strava_threshold_zones TO matt;\n
      CREATE DATABASE strava_threshold_zones_test;\n
      GRANT ALL PRIVILEGES ON DATABASE strava_threshold_zones_test TO matt;\nEOSQL\" > /docker-entrypoint-initdb.d/init-databases.sh;
      docker-entrypoint.sh postgres"
